import { Linking, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { contactEmail } from "../config/Config";
import { vh, vw } from "../config/Toolbox";

const CreditsModal = (props) => {
    const H1 = (props) => <Text style={styles.h1}>{props.children}</Text>
    const H2 = (props) => <Text style={styles.h2}>{props.children}</Text>
    const P = (props) => <Text style={styles.p}>{props.children}</Text>
    const UL = (props) => <View style={styles.ul}>{props.children}</View>
    const LI = (props) => <View style={styles.li}><Text style={styles.p}>    • {props.children}</Text></View>
    const A = (props) => <Text style={styles.a} onPress={() => Linking.openURL(props.href)}>{props.children}</Text>;

    const generateUL = (...texts) => {
        const entries = texts.map((text, i) => <LI key={i}><P>{text}</P></LI>);
        return ( <UL>{entries}</UL> );
    };

    return (
        <Modal
            transparent={true}
            onRequestClose={props.confirm}
            visible={props.isModalVisible}
        >
            <Pressable style={styles.absolute} onPress={props.confirm} />

            <ScrollView style={styles.body} overScrollMode="never" showsVerticalScrollIndicator={false}>
                <View style={styles.textContainer}>
                    <H1>Credits</H1>

                    <H2>Developers</H2>
                    { generateUL("Travis Heavener") }

                    <H2>Frameworks & Services</H2>
                    { generateUL(
                        "React Native", "Expo", "EAS CLI", "Git", "GitHub",
                        <P>Terms of Service generated by <A href="https://www.termsfeed.com/terms-conditions-generator/">TermsFeed Terms and Conditions Generator</A></P>,
                        <P>Privacy Policy created by <A href="https://privacypolicytemplate.net/">privacypolicytemplate.net</A></P>,
                        <P>Privacy Policy modified/generated by <A href="https://app-privacy-policy-generator.nisrulz.com/">App Privacy Policy Generator</A></P>
                    ) }

                    <H2>Important Links</H2>
                    { generateUL(
                        <A href="https://github.com/travis-heavener/seniorresearch">GitHub Repository</A>
                    ) }

                    <H2>Contact Information</H2>
                    { generateUL("By email: " + contactEmail) }

                    <Pressable style={styles.acceptButton} onPress={props.confirm}>
                        <Text style={styles.acceptButtonText}>Okay</Text>
                    </Pressable>
                </View>
            </ScrollView>

            {/* shows border over text */}
            <View style={styles.containerBorder} pointerEvents="none" />
        </Modal>
    )
};

export default CreditsModal;

const styles = StyleSheet.create({
    absolute: {
        position: "absolute",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: "#0006"
    },
    body: {
        position: "absolute",
        left: vw(12.5),
        right: vw(12.5),
        top: vh(25),
        bottom: vh(25),
        paddingHorizontal: vw(4),
        backgroundColor: "#f0f0f0",
        borderRadius: vh(2.5)
    },
    textContainer: {
        width: "100%",
        marginVertical: vh(2),
        overflow: "hidden"
    },
    containerBorder: {
        position: "absolute",
        left: vw(12.5),
        right: vw(12.5),
        top: vh(25),
        bottom: vh(25),
        borderRadius: vh(2.5),
        borderWidth: vh(0.5),
        borderColor: "#c0c0c0"
    },
    h1: {
        marginVertical: vh(1),
        textAlign: "center",
        fontFamily: "Arial",
        fontWeight: "800",
        fontSize: vh(3),
        lineHeight: vh(4),
        color: "#000"
    },
    h2: {
        marginTop: vh(1),
        marginBottom: vh(0.5),
        textAlign: "left",
        fontFamily: "Arial",
        fontWeight: "800",
        fontSize: vh(2.25),
        lineHeight: vh(3.5),
        color: "#333"
    },
    h3: {
        marginTop: vh(1),
        marginBottom: vh(0.5),
        textAlign: "left",
        fontFamily: "Arial",
        fontWeight: "800",
        fontSize: vh(2),
        lineHeight: vh(3.25),
        color: "#444"
    },
    p: {
        textAlign: "left",
        fontFamily: "Arial",
        fontWeight: "400",
        fontSize: vh(1.625),
        lineHeight: vh(2.125),
        color: "#111"
    },
    a: {
        textAlign: "left",
        fontFamily: "Arial",
        fontWeight: "400",
        fontSize: vh(1.625),
        lineHeight: vh(2.125),
        textDecorationLine: "underline",
        color: "blue"
    },
    ul: {
        width: "100%",
        flexDirection: "column"
    },
    li: {
        marginVertical: vh(0.25)
    },
    acceptButton: {
        width: vw(26),
        height: vh(6),
        marginTop: vh(2),
        alignSelf: "center"
    },
    acceptButtonText: {
        flex: 1,
        textAlign: "center",
        textAlignVertical: "center",
        fontWeight: "600",
        fontSize: vh(2.625),
        backgroundColor: "#b0b0ff",
        borderWidth: vh(0.33),
        borderColor: "#222",
        borderRadius: vh(1.25)
    }
});